In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sms

In [4]:
df=pd.read_csv("cereal.csv")
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB

In [6]:
#Question 1 
pd.crosstab(df.mfr,df.type)

type   C  H
mfr
A      0  1
G     22  0
K     23  0
N      5  1
P      9  0
Q      7  1
R      8  0

In [22]:
#Question 2 
ndf = df.iloc[:,3:11]
ndf
ndf.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,106.883117,2.402597,1.012987,181.298701,1.781818,14.798701,6.922078,85.298701
std,19.484119,0.892361,1.006473,60.089859,1.511250,3.881688,4.444885,52.798042
min,50.000000,1.000000,0.000000,15.000000,0.000000,5.000000,-1.000000,-1.000000
25%,100.000000,2.000000,0.000000,140.000000,1.000000,12.000000,3.000000,40.000000
50%,110.000000,2.000000,1.000000,185.000000,1.500000,14.500000,7.000000,90.000000
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,110.000000
max,160.000000,4.000000,5.000000,320.000000,6.000000,23.000000,15.000000,240.000000

In [8]:
#Question 3 - For missing values find and replace with arithmetic mean of the attributes
df.isnull().any()

name        False
mfr         False
type        False
calories    False
protein     False
fat         False
sodium      False
fiber       False
carbo       False
sugars      False
potass      False
vitamins    False
shelf       False
weight      False
cups        False
rating      False
dtype: bool

In [21]:
#Question 3 - Replace missing values with mean 

newdf = df.replace(-1,df[["protein","fat", "sodium", "fiber","sugars","potass","vitamins"]].mean())

In [10]:
#Question 4 - Find and replace outliers with median 

for col in ["protein","fat", "sodium", "fiber","carbo","sugars","potass","vitamins"]:

    Q1 = df[col].quantile(0.25)


    Q3 = df[col].quantile(0.75)


    IQR = Q3 - Q1


    upper = Q3+ 1.5 * IQR
    lower = Q1- 1.5*IQR
    df.loc[df[col]>upper, col] = np.NaN
    df.loc[df[col]<lower, col] = np.NaN
    df[col].fillna(df[col].median(), inplace=True)

In [11]:
#Question 5 - Compare the 5 number summary before and after preprocessing
newdf.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,106.883117,2.545455,1.012987,159.675325,2.151948,14.597403,7.024962,98.599427,28.246753,2.207792,1.029610,0.821039,42.665705
std,19.484119,1.094790,1.006473,83.832295,2.383364,4.278956,4.349770,69.479240,22.342523,0.832524,0.150477,0.232716,14.047289
min,50.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,15.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,130.000000,1.000000,12.000000,3.000000,45.000000,25.000000,1.000000,1.000000,0.670000,33.174094
50%,110.000000,3.000000,1.000000,180.000000,2.000000,14.000000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.400208
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.828392
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [12]:
#Question 6 -  Are the attributes calories and consumer rating correlated?
newdf[['calories','rating']].corr()

          calories    rating
calories  1.000000 -0.689376
rating   -0.689376  1.000000

In [13]:
#Question 7 - Are the attributes mfr and consumer rating correlated 
newdf[['mfr','rating']].corr()

        rating
rating     1.0

In [14]:
#Question 8 - Which is the best Vs worst cereal in terms of consumer rating
print("Best cereal :" ,df.loc[df["rating"].idxmax(),"name"])
print("Worst cereal :" ,df.loc[df["rating"].idxmin(),"name"])

Best cereal : All-Bran with Extra Fiber
Worst cereal : Cap'n'Crunch

In [15]:
#Question 9 -  Which is the best Vs worst cereal in terms of calories?
print("Best cereal :" ,df.loc[df["calories"].idxmin(),"name"])
print("Worst cereal :" ,df.loc[df["calories"].idxmax(),"name"])

Best cereal : All-Bran with Extra Fiber
Worst cereal : Mueslix Crispy Blend

In [16]:
#Question 10 - Rate the top 5 cereals in terms of user rating
df2=newdf.sort_values(by="rating",ascending=False)
df2.head(5)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0.0,330.0,25,3,1.00,0.50,93.704912
64,Shredded Wheat 'n'Bran,N,C,90,3,0,0,4.0,19.0,0.0,140.0,0,1,1.00,0.67,74.472949
65,Shredded Wheat spoon size,N,C,90,3,0,0,3.0,20.0,0.0,120.0,0,1,1.00,0.67,72.801787
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6.0,280.0,25,3,1.00,0.33,68.402973
63,Shredded Wheat,N,C,80,2,0,0,3.0,16.0,0.0,95.0,0,1,0.83,1.00,68.235885

In [17]:
#Question 11 - Identify the cereal with highest sodium 
newdf.loc[df["sodium"].idxmax(),'name']

'Product 19'

In [18]:
#Question 12 - Identify the cereal with the lowest carbohydrate 
newdf.loc[df["carbo"].idxmin(),'name']

'100% Bran'

In [19]:
#Question 13 - Are the variables shelf and sugar correlated?
newdf[['shelf','sugars']].corr()

           shelf    sugars
shelf   1.000000  0.067868
sugars  0.067868  1.000000

In [20]:
#Question 14 - Identify the manufacturer of the cereal with the highest sugar content 
newdf.loc[newdf["sugars"].idxmax(),'mfr']

'P'